new digest-based versioning; support v2 APIs
notable changes:

* removed `server_args`; it led to too much coupling with the docker
  CLI.

* added `insecure_registries` in its place, which is now used for
  both the CLI and the now-native-Go 'check' script

* `out` always pushes; this is because a digest can only be returned by
  pushing

* `check` works again!

* `in` will fetch exactly the digest that it was told; previously it
  would fetch the image and hope it got the same image ID

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -24,9 +24,9 @@ cat > $payload <&0
 
 cd $source
 
-server_args=$(jq -r '.source.server_args // ""' < $payload)
+insecure_registries=$(jq -r '.source.insecure_registries // [] | join(" ")' < $payload)
 
-start_docker "$server_args"
+start_docker "$insecure_registries"
 
 username=$(jq -r '.source.username // ""' < $payload)
 password=$(jq -r '.source.password // ""' < $payload)
@@ -85,7 +85,7 @@ rootfs="$(jq -r '.params.rootfs' < $payload)"
 
 if [ -n "$build" ]; then
   if [ "$cache" = "true" ]; then
-    docker_pull "${repository}:${tag_name}";
+    docker_pull "${repository}:${tag_name}"
   fi
 
   docker build -t "${repository}:${tag_name}" "$build"
@@ -105,22 +105,39 @@ else
   exit 1
 fi
 
-image=$(docker_image "$repository" "${tag_name}")
+image_id="$(docker_image "$repository" "$tag_name")"
 
 if [ "$rootfs" = "true" ]; then
-  docker run --cidfile=container.cid "$image" echo container created
+  docker run --cidfile=container.cid "$image_id" echo container created
   docker export $(cat container.cid) > ${destination}/rootfs.tar
 fi
 
-if [ "$push" = "null" ] || [ "$push" = "true" ]; then
-  docker push "${repository}:${tag_name}"
+# afaict there's no clean way to get the digest after a push. docker prints
+# this line at the end at least:
+#
+#   (tagname): digest: (digest) size: (size)
+#
+# so just parse it out
+
+# careful to not let 'tee' mask exit status
+
+{
+  if ! docker push "${repository}:${tag_name}"; then
+    touch /tmp/push-failed
+  fi
+} | tee push-output
+
+if [ -e /tmp/push-failed ]; then
+  exit 1
 fi
+
+digest="$(tail -1 push-output | awk '{print $3}')"
 
 jq -n "{
   version: {
-    image: $(echo $image | jq -R .)
+    digest: $(echo $digest | jq -R .)
   },
   metadata: [
-    { name: \"image\", value: $(echo $image | head -c 12 | jq -R .) }
+    { name: \"image\", value: $(echo $image_id | head -c 12 | jq -R .) }
   ]
 }" >&3
