fix tests / bad merge

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -25,7 +25,6 @@ cat > $payload <&0
 cd $source
 
 insecure_registries=$(jq -r '.source.insecure_registries // [] | join(" ")' < $payload)
-
 registry_mirror=$(jq -r '.source.registry_mirror // ""' < $payload)
 
 username=$(jq -r '.source.username // ""' < $payload)
@@ -61,7 +60,11 @@ log_in "$username" "$password" "$registry"
 
 tag_source=$(jq -r '.source.tag // "latest"' < $payload)
 pull_image_id=$(jq -r '.params.pull_image_id // ""' < $payload)
-tag_params=$(jq -r '.params.tag // ""' < $payload)
+tag_params=$(jq -r '.params.tag_file // ""' < $payload)
+# for backwards compatibility, check `tag` if `tag_file` is empty
+if [ -z "$tag_params" ]; then
+  tag_params=$(jq -r '.params.tag // ""' < $payload)
+fi
 tag_prefix=$(jq -r '.params.tag_prefix // ""' < $payload)
 additional_tags=$(jq -r '.params.additional_tags // ""' < $payload)
 need_tag_as_latest=$(jq -r '.params.tag_as_latest // "false"' < $payload)
@@ -71,6 +74,7 @@ labels=$(jq -r '.params.labels // {}' < $payload)
 labels_file=$(jq -r '.params.labels_file // ""' < $payload)
 mirror_repositories=$(jq -r '.params.mirror_repositories // empty' < $payload)
 static_tags=$(jq -r '.params.static_tags // ""' < $payload)
+
 
 tag_name=""
 if [ -n "$tag_params" ]; then
@@ -183,28 +187,39 @@ elif [ -n "$build" ]; then
   if [ "${#build_arg_keys[@]}" -gt 0 ]; then
     for key in "${build_arg_keys[@]}"; do
       value=$(echo "$build_args" | jq -r --arg "k" "$key" '.[$k]')
+      for var in BUILD_ID BUILD_NAME BUILD_JOB_NAME BUILD_PIPELINE_NAME BUILD_TEAM_NAME ATC_EXTERNAL_URL; do
+        value="${value//\$$var/${!var:-}}"
+        value="${value//\$\{$var\}/${!var:-}}"
+      done
       expanded_build_args+=("--build-arg")
       expanded_build_args+=("${key}=${value}")
     done
   fi
 
   if [ -n "$build_args_file" ]; then
-    build_arg_keys=($(jq -r 'keys | join(" ")' "$build_args_file"))
-    if [ "${#build_arg_keys[@]}" -gt 0 ]; then
-      for key in "${build_arg_keys[@]}"; do
-        value=$(jq -r --arg "k" "$key" '.[$k]' "$build_args_file")
-        expanded_build_args+=("--build-arg")
-        expanded_build_args+=("${key}=${value}")
-      done
+    if jq . "$build_args_file" >/dev/null 2>&1; then
+      build_arg_keys=($(jq -r 'keys | join(" ")' "$build_args_file"))
+      if [ "${#build_arg_keys[@]}" -gt 0 ]; then
+        for key in "${build_arg_keys[@]}"; do
+          value=$(jq -r --arg "k" "$key" '.[$k]' "$build_args_file")
+          expanded_build_args+=("--build-arg")
+          expanded_build_args+=("${key}=${value}")
+        done
+      fi
+    else
+      echo "Failed to parse build_args_file ($build_args_file)"
+      exit 1
     fi
   fi
+
+  expanded_labels=()
 
   label_keys=($(echo "$labels" | jq -r 'keys | join(" ")'))
   if [ "${#label_keys[@]}" -gt 0 ]; then
     for key in "${label_keys[@]}"; do
       value=$(echo "$labels" | jq -r --arg "k" "$key" '.[$k]')
-      expanded_build_args+=("--label")
-      expanded_build_args+=("${key}=${value}")
+      expanded_labels+=("--label")
+      expanded_labels+=("${key}=${value}")
     done
   fi
 
@@ -213,8 +228,8 @@ elif [ -n "$build" ]; then
     if [ "${#labels_keys[@]}" -gt 0 ]; then
       for key in "${labels_keys[@]}"; do
         value=$(jq -r --arg "k" "$key" '.[$k]' "$labels_file")
-        expanded_build_args+=("--label")
-        expanded_build_args+=("${key}=${value}")
+        expanded_labels+=("--label")
+        expanded_labels+=("${key}=${value}")
       done
     fi
   fi
@@ -240,7 +255,7 @@ elif [ -n "$build" ]; then
     done
   fi
 
-  docker build -t "${repository}:${tag_name}" "${target[@]}" "${expanded_build_args[@]}" -f "$dockerfile" $cache_from "$build"
+  docker build -t "${repository}:${tag_name}" "${target[@]}" "${expanded_build_args[@]}" "${expanded_labels[@]}" -f "$dockerfile" $cache_from "$build"
 elif [ -n "$load_file" ]; then
   if [ -n "$load_repository" ]; then
     docker load -i "$load_file"
